### ISSUE TITLE
Timeout logs

### ISSUE THREAD

**Issue by jbusuttil83** [FluBBaOfWard/openhab2-addons#2]
Hi, first of all a big well done for developing this addon. I installed it on Openhab and it works very well.
 What I am noticing, is that when my PS4 is completely turned off, a log is being written as info 
'Fetch status exception: Receive timed out'.

Is it possible that we make this log maybe configurable? or maybe not log each occurrence. I am asking this because it is filling up my log file quite quickly with a log entry every 10 secs. If you are ok with it, I can check if I can do it my self and do a PR you.

**Comment by FluBBaOfWard** [comment]
I can easily set it to debug or trace instead, is that good enough right now?

**Comment by jbusuttil83** [comment]
Yes debug would be very good
